[project]
name = "symbolite"
version = "1.1.1"
description = "A minimalistic symbolic package."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
  { name = "Hernán E. Grecco", email = "hernan.grecco@gmail.com" },
  { name = "Mauro Silberberg", email = "maurosilber@gmail.com" },
]
keywords = ["symbolic"]
classifiers = [
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development :: Libraries",
]
dependencies = ["typing-extensions>=4.15"]

[project.urls]
changelog = "https://github.com/dyscolab/symbolite/blob/main/CHANGES"
homepage = "https://github.com/dyscolab/symbolite"
issues = "https://github.com/dyscolab/symbolite/issues"

[build-system]
requires = ["uv_build>=0.12"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = "--import-mode=importlib --doctest-modules"
doctest_optionflags = "NUMBER"
filterwarnings = "ignore:No libsl provided, defaulting to Python standard library."
pythonpath = "."
testpaths = ["src/symbolite/testsuite"]

[tool.ruff.format]
docstring-code-format = true

[tool.tombi]
toml-version = "v1.1.0"
